### ISSUE TITLE
FS (FAT12)

### ISSUE THREAD

**Issue by coffee100percnt** [corruptmemry/hydrogenos#7]
когда

**Comment by TheAirBlow** [comment]
Иди нахуй

**Comment by coffee100percnt** [comment]
аир делай фс

**Comment by corruptmemry** [comment]
согласен мы ждем!!!!

**Comment by TheAirBlow** [comment]
Отсосите

**Comment by TheAirBlow** [comment]
Если ты откроешь ты ты даун тупой

**Comment by coffee100percnt** [comment]
> Отсосите

быстро делать пошёл
гей

**Comment by coffee100percnt** [comment]
# ля ты крыса

**Comment by corruptmemry** [comment]
# нюхай бебру

**Comment by TheAirBlow** [comment]
Карапт делай сам, спизди код

**Comment by deviceesamp** [comment]
хХВСАПВА-П=-АВПФВАЩАОВЫФЩАОВЫЩФОАДВЫФОАВЛЫФОАВЫЖФОАЛЛЫВАЛОЫЛВОАЫВАВЫФАВЫАЫВВЫ

**Comment by coffee100percnt** [comment]
> Карапт делай сам, спизди код

ну и гей

**Comment by corruptmemry** [comment]
пиши сам с нуля без пасты

**Comment by coffee100percnt** [comment]
красть не красиво

**Comment by deviceesamp** [comment]
-__-к9е4-5069%:;%:№;%№;№:;№:№:%:%*()*()*()*();*№)(;*)(№;_(№№*_№(*"_;*№"(;*№)(*;)(№*;(№_;*№(+*";)(*"*;"*;)("*);(*")(;*№()*;)№*(;)*№)(;*_№(*(№*;()№*;)(№*;_*")(;*"(;*)("№;*()№*;(*№)(;*№)(*("*№;3

**Comment by deviceesamp** [comment]
**### петушара**

**Comment by coffee100percnt** [comment]
[ ] фс не сделана
- [ ] аир гей

**Comment by deviceesamp** [comment]
### **ПЕТУШАРА**

**Comment by TheAirBlow** [comment]
Идите нахуй

**Comment by TheAirBlow** [comment]
Генту хуйня

**Comment by coffee100percnt** [comment]
не пойдём

**Comment by coffee100percnt** [comment]
> Генту хуйня

- [x] генту топ
- [x] аир гей

**Comment by coffee100percnt** [comment]
@TheAirBlow делай фс

**Comment by coffee100percnt** [comment]
ладно

**Comment by corruptmemry** [comment]
делай фс

**Comment by coffee100percnt** [comment]
@TheAirBlow делай фс

**Comment by coffee100percnt** [comment]
я крутой я пишу с почты

**Comment by TheAirBlow** [comment]
Иди нахуй я тоже

вт, 7 сент. 2021 г., 23:44 coffee100percnt ***@***.***>:

**Comment by corruptmemry** [comment]
я тоже

ср, 8 сент. 2021 г. в 12:16, TheAirBlow ***@***.***>:

**Comment by TheAirBlow** [comment]
карапт делай фс

**Comment by coffee100percnt** [comment]
Аир лох не делает фс

**Comment by corruptmemry** [comment]
когда фс аир

**Comment by corruptmemry** [comment]
когда фс

**Comment by corruptmemry** [comment]
хуй

**Comment by corruptmemry** [comment]
сасите я сделал фс
